baseurl = "https://buwidi.pages.dev/"  # Include trailing slash
title = "WildanFauzy.com"
#theme = "hugo-swift-theme"
# theme = "swift"
author = "Steve Francia"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = false
paginate = 8
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
[permalinks]
post = "/:slug/"

[params]
  [params.designer]
    name = "wilfauzy"
    url = "https://twitter.com/wilfauzy"
  [[params.authors]]
    name = "wilfauzy" # can be nickname # if fullName 👇🏻 isn't set, name will be displayed on author card
    fullName = "Wildan Fauzy" # optional. If set, it will display on author card
    bio = "Penulis Amatiran"
    photo = "img/about. img"
    url = "https://wildanfauzy.com"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
   twitter = "wilfauzy" # twitter handle e.g @weru
  # logo = "logo.png"
  # author = "Weru" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  # blogDir = "blogFolderName" # uncomment and edit to exclude normal pages ... see issue #57
# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "username"  # GitHub/GitLab user name
#   repository = "repo"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

[menu]
  [[menu.main]]
    name = "Tentang"
    url = "tentang/"
    weight = 2
  [[menu.main]]
  name = "Search"
  url = "https://search.wildanfauzy.com"
  weight = 3
  [[menu.main]]
  name = "Log in"
  url = "https://app.wildanfauzy.com/"
  weight = 4
  [[menu.main]]
  name = "Surat"
  url = "https://surat.wildanfauzy.com"
  weight = 5
  [[menu.main]]
  name = "Perpus"
  url = "https:///perpus.wildanfauzy.com"
  weight = 6
